//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BildirimService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", ConfigurationName="BildirimService.BKST_EXT_READ_SERVICE_PortType")]
    public interface BKST_EXT_READ_SERVICE_PortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="BKST_EXT_Services_BKST_EXT_READ_SERVICE_Binder_KeyStatusCheck", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BildirimService.KeyStatusCheckResponse KeyStatusCheck(BildirimService.KeyStatusCheckRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BKST_EXT_Services_BKST_EXT_READ_SERVICE_Binder_KeyStatusCheck", ReplyAction="*")]
        System.Threading.Tasks.Task<BildirimService.KeyStatusCheckResponse> KeyStatusCheckAsync(BildirimService.KeyStatusCheckRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BKST_EXT_Services_BKST_EXT_READ_SERVICE_Binder_TransactionListProduction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BildirimService.TransactionListProductionResponse TransactionListProduction(BildirimService.TransactionListProductionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BKST_EXT_Services_BKST_EXT_READ_SERVICE_Binder_TransactionListProduction", ReplyAction="*")]
        System.Threading.Tasks.Task<BildirimService.TransactionListProductionResponse> TransactionListProductionAsync(BildirimService.TransactionListProductionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BKST_EXT_Services_BKST_EXT_READ_SERVICE_Binder_GetCountryName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BildirimService.GetCountryNameResponse GetCountryName(BildirimService.GetCountryNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BKST_EXT_Services_BKST_EXT_READ_SERVICE_Binder_GetCountryName", ReplyAction="*")]
        System.Threading.Tasks.Task<BildirimService.GetCountryNameResponse> GetCountryNameAsync(BildirimService.GetCountryNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BKST_EXT_Services_BKST_EXT_READ_SERVICE_Binder_SendXMLNotification_Dealer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BildirimService.SendXMLNotification_DealerResponse SendXMLNotification_Dealer(BildirimService.SendXMLNotification_DealerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BKST_EXT_Services_BKST_EXT_READ_SERVICE_Binder_SendXMLNotification_Dealer", ReplyAction="*")]
        System.Threading.Tasks.Task<BildirimService.SendXMLNotification_DealerResponse> SendXMLNotification_DealerAsync(BildirimService.SendXMLNotification_DealerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BKST_EXT_Services_BKST_EXT_READ_SERVICE_Binder_CarrierDetailList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BildirimService.CarrierDetailListResponse CarrierDetailList(BildirimService.CarrierDetailListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BKST_EXT_Services_BKST_EXT_READ_SERVICE_Binder_CarrierDetailList", ReplyAction="*")]
        System.Threading.Tasks.Task<BildirimService.CarrierDetailListResponse> CarrierDetailListAsync(BildirimService.CarrierDetailListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BKST_EXT_Services_BKST_EXT_READ_SERVICE_Binder_CarrierDetailList_Wholesaler", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BildirimService.CarrierDetailList_WholesalerResponse CarrierDetailList_Wholesaler(BildirimService.CarrierDetailList_WholesalerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BKST_EXT_Services_BKST_EXT_READ_SERVICE_Binder_CarrierDetailList_Wholesaler", ReplyAction="*")]
        System.Threading.Tasks.Task<BildirimService.CarrierDetailList_WholesalerResponse> CarrierDetailList_WholesalerAsync(BildirimService.CarrierDetailList_WholesalerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BKST_EXT_Services_BKST_EXT_READ_SERVICE_Binder_TransactionList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BildirimService.TransactionListResponse TransactionList(BildirimService.TransactionListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BKST_EXT_Services_BKST_EXT_READ_SERVICE_Binder_TransactionList", ReplyAction="*")]
        System.Threading.Tasks.Task<BildirimService.TransactionListResponse> TransactionListAsync(BildirimService.TransactionListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BKST_EXT_Services_BKST_EXT_READ_SERVICE_Binder_GetCompanyName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BildirimService.GetCompanyNameResponse GetCompanyName(BildirimService.GetCompanyNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BKST_EXT_Services_BKST_EXT_READ_SERVICE_Binder_GetCompanyName", ReplyAction="*")]
        System.Threading.Tasks.Task<BildirimService.GetCompanyNameResponse> GetCompanyNameAsync(BildirimService.GetCompanyNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BKST_EXT_Services_BKST_EXT_READ_SERVICE_Binder_SendXMLNotification", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BildirimService.SendXMLNotificationResponse SendXMLNotification(BildirimService.SendXMLNotificationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BKST_EXT_Services_BKST_EXT_READ_SERVICE_Binder_SendXMLNotification", ReplyAction="*")]
        System.Threading.Tasks.Task<BildirimService.SendXMLNotificationResponse> SendXMLNotificationAsync(BildirimService.SendXMLNotificationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BKST_EXT_Services_BKST_EXT_READ_SERVICE_Binder_StockCheck", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BildirimService.StockCheckResponse StockCheck(BildirimService.StockCheckRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BKST_EXT_Services_BKST_EXT_READ_SERVICE_Binder_StockCheck", ReplyAction="*")]
        System.Threading.Tasks.Task<BildirimService.StockCheckResponse> StockCheckAsync(BildirimService.StockCheckRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BKST_EXT_Services_BKST_EXT_READ_SERVICE_Binder_GetCompanyNameByGLN_PN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BildirimService.GetCompanyNameByGLN_PNResponse GetCompanyNameByGLN_PN(BildirimService.GetCompanyNameByGLN_PNRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BKST_EXT_Services_BKST_EXT_READ_SERVICE_Binder_GetCompanyNameByGLN_PN", ReplyAction="*")]
        System.Threading.Tasks.Task<BildirimService.GetCompanyNameByGLN_PNResponse> GetCompanyNameByGLN_PNAsync(BildirimService.GetCompanyNameByGLN_PNRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BKST_EXT_Services_BKST_EXT_READ_SERVICE_Binder_GetHistory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BildirimService.GetHistoryResponse GetHistory(BildirimService.GetHistoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BKST_EXT_Services_BKST_EXT_READ_SERVICE_Binder_GetHistory", ReplyAction="*")]
        System.Threading.Tasks.Task<BildirimService.GetHistoryResponse> GetHistoryAsync(BildirimService.GetHistoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BKST_EXT_Services_BKST_EXT_READ_SERVICE_Binder_SendXMLNotification_Wholesaler", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BildirimService.SendXMLNotification_WholesalerResponse SendXMLNotification_Wholesaler(BildirimService.SendXMLNotification_WholesalerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BKST_EXT_Services_BKST_EXT_READ_SERVICE_Binder_SendXMLNotification_Wholesaler", ReplyAction="*")]
        System.Threading.Tasks.Task<BildirimService.SendXMLNotification_WholesalerResponse> SendXMLNotification_WholesalerAsync(BildirimService.SendXMLNotification_WholesalerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BKST_EXT_Services_BKST_EXT_READ_SERVICE_Binder_TransactionDetailList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BildirimService.TransactionDetailListResponse TransactionDetailList(BildirimService.TransactionDetailListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BKST_EXT_Services_BKST_EXT_READ_SERVICE_Binder_TransactionDetailList", ReplyAction="*")]
        System.Threading.Tasks.Task<BildirimService.TransactionDetailListResponse> TransactionDetailListAsync(BildirimService.TransactionDetailListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BKST_EXT_Services_BKST_EXT_READ_SERVICE_Binder_CarrierDetailList_Dealer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BildirimService.CarrierDetailList_DealerResponse CarrierDetailList_Dealer(BildirimService.CarrierDetailList_DealerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BKST_EXT_Services_BKST_EXT_READ_SERVICE_Binder_CarrierDetailList_Dealer", ReplyAction="*")]
        System.Threading.Tasks.Task<BildirimService.CarrierDetailList_DealerResponse> CarrierDetailList_DealerAsync(BildirimService.CarrierDetailList_DealerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BKST_EXT_Services_BKST_EXT_READ_SERVICE_Binder_GetProductName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BildirimService.GetProductNameResponse GetProductName(BildirimService.GetProductNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BKST_EXT_Services_BKST_EXT_READ_SERVICE_Binder_GetProductName", ReplyAction="*")]
        System.Threading.Tasks.Task<BildirimService.GetProductNameResponse> GetProductNameAsync(BildirimService.GetProductNameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KeyStatusCheck", WrapperNamespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", IsWrapped=true)]
    public partial class KeyStatusCheckRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string Key;
        
        public KeyStatusCheckRequest()
        {
        }
        
        public KeyStatusCheckRequest(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KeyStatusCheckResponse", WrapperNamespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", IsWrapped=true)]
    public partial class KeyStatusCheckResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int> KEY_STATUS;
        
        public KeyStatusCheckResponse()
        {
        }
        
        public KeyStatusCheckResponse(System.Nullable<int> KEY_STATUS)
        {
            this.KEY_STATUS = KEY_STATUS;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE")]
    public partial class TransactionListProductionResult
    {
        
        private string iD_TRANSACTIONField;
        
        private string dOCUMENT_NUMBERField;
        
        private string dOCUMENT_DATEField;
        
        private string sENDERField;
        
        private string rECEIVERField;
        
        private string rETURN_NOTEField;
        
        private string aCTION_TYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string ID_TRANSACTION
        {
            get
            {
                return this.iD_TRANSACTIONField;
            }
            set
            {
                this.iD_TRANSACTIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string DOCUMENT_NUMBER
        {
            get
            {
                return this.dOCUMENT_NUMBERField;
            }
            set
            {
                this.dOCUMENT_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string DOCUMENT_DATE
        {
            get
            {
                return this.dOCUMENT_DATEField;
            }
            set
            {
                this.dOCUMENT_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string SENDER
        {
            get
            {
                return this.sENDERField;
            }
            set
            {
                this.sENDERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string RECEIVER
        {
            get
            {
                return this.rECEIVERField;
            }
            set
            {
                this.rECEIVERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string RETURN_NOTE
        {
            get
            {
                return this.rETURN_NOTEField;
            }
            set
            {
                this.rETURN_NOTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string ACTION_TYPE
        {
            get
            {
                return this.aCTION_TYPEField;
            }
            set
            {
                this.aCTION_TYPEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE")]
    public partial class TransactionDetailResult
    {
        
        private string bARKODField;
        
        private string sERIAL_NUMBERField;
        
        private string lOT_NUMBERField;
        
        private string kAREKODField;
        
        private string cARRIER_LABEL1Field;
        
        private string cARRIER_LABEL2Field;
        
        private string pRODUCTION_DATEField;
        
        private string eXPIRATION_DATEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string BARKOD
        {
            get
            {
                return this.bARKODField;
            }
            set
            {
                this.bARKODField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string SERIAL_NUMBER
        {
            get
            {
                return this.sERIAL_NUMBERField;
            }
            set
            {
                this.sERIAL_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string LOT_NUMBER
        {
            get
            {
                return this.lOT_NUMBERField;
            }
            set
            {
                this.lOT_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string KAREKOD
        {
            get
            {
                return this.kAREKODField;
            }
            set
            {
                this.kAREKODField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string CARRIER_LABEL1
        {
            get
            {
                return this.cARRIER_LABEL1Field;
            }
            set
            {
                this.cARRIER_LABEL1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string CARRIER_LABEL2
        {
            get
            {
                return this.cARRIER_LABEL2Field;
            }
            set
            {
                this.cARRIER_LABEL2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string PRODUCTION_DATE
        {
            get
            {
                return this.pRODUCTION_DATEField;
            }
            set
            {
                this.pRODUCTION_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string EXPIRATION_DATE
        {
            get
            {
                return this.eXPIRATION_DATEField;
            }
            set
            {
                this.eXPIRATION_DATEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE")]
    public partial class History_Detail
    {
        
        private string bARKODField;
        
        private string sERIAL_NUMBERField;
        
        private string lOT_NUMBERField;
        
        private string kAREKODField;
        
        private string cARRIER_LABEL1Field;
        
        private string cARRIER_LABEL2Field;
        
        private string pRODUCTION_DATEField;
        
        private string eXPIRATION_DATEField;
        
        private string dOCUMENT_NUMBERField;
        
        private string dOCUMENT_DATEField;
        
        private string sENDERField;
        
        private string rECEIVERField;
        
        private string eXPORT_COMPANY_NAMEField;
        
        private string eXPORT_COUNTRY_NAMEField;
        
        private string iMPORT_COMPANY_NAMEField;
        
        private string iMPORT_COUNTRY_NAMEField;
        
        private string oPERATION_DATEField;
        
        private string aCTION_TYPEField;
        
        private string dEACTIVATION_CODEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string BARKOD
        {
            get
            {
                return this.bARKODField;
            }
            set
            {
                this.bARKODField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string SERIAL_NUMBER
        {
            get
            {
                return this.sERIAL_NUMBERField;
            }
            set
            {
                this.sERIAL_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string LOT_NUMBER
        {
            get
            {
                return this.lOT_NUMBERField;
            }
            set
            {
                this.lOT_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string KAREKOD
        {
            get
            {
                return this.kAREKODField;
            }
            set
            {
                this.kAREKODField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string CARRIER_LABEL1
        {
            get
            {
                return this.cARRIER_LABEL1Field;
            }
            set
            {
                this.cARRIER_LABEL1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string CARRIER_LABEL2
        {
            get
            {
                return this.cARRIER_LABEL2Field;
            }
            set
            {
                this.cARRIER_LABEL2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string PRODUCTION_DATE
        {
            get
            {
                return this.pRODUCTION_DATEField;
            }
            set
            {
                this.pRODUCTION_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string EXPIRATION_DATE
        {
            get
            {
                return this.eXPIRATION_DATEField;
            }
            set
            {
                this.eXPIRATION_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public string DOCUMENT_NUMBER
        {
            get
            {
                return this.dOCUMENT_NUMBERField;
            }
            set
            {
                this.dOCUMENT_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string DOCUMENT_DATE
        {
            get
            {
                return this.dOCUMENT_DATEField;
            }
            set
            {
                this.dOCUMENT_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public string SENDER
        {
            get
            {
                return this.sENDERField;
            }
            set
            {
                this.sENDERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public string RECEIVER
        {
            get
            {
                return this.rECEIVERField;
            }
            set
            {
                this.rECEIVERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public string EXPORT_COMPANY_NAME
        {
            get
            {
                return this.eXPORT_COMPANY_NAMEField;
            }
            set
            {
                this.eXPORT_COMPANY_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=13)]
        public string EXPORT_COUNTRY_NAME
        {
            get
            {
                return this.eXPORT_COUNTRY_NAMEField;
            }
            set
            {
                this.eXPORT_COUNTRY_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=14)]
        public string IMPORT_COMPANY_NAME
        {
            get
            {
                return this.iMPORT_COMPANY_NAMEField;
            }
            set
            {
                this.iMPORT_COMPANY_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=15)]
        public string IMPORT_COUNTRY_NAME
        {
            get
            {
                return this.iMPORT_COUNTRY_NAMEField;
            }
            set
            {
                this.iMPORT_COUNTRY_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=16)]
        public string OPERATION_DATE
        {
            get
            {
                return this.oPERATION_DATEField;
            }
            set
            {
                this.oPERATION_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=17)]
        public string ACTION_TYPE
        {
            get
            {
                return this.aCTION_TYPEField;
            }
            set
            {
                this.aCTION_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=18)]
        public string DEACTIVATION_CODE
        {
            get
            {
                return this.dEACTIVATION_CODEField;
            }
            set
            {
                this.dEACTIVATION_CODEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE")]
    public partial class TransactionResult
    {
        
        private string iD_TRANSACTIONField;
        
        private string dOCUMENT_NUMBERField;
        
        private string dOCUMENT_DATEField;
        
        private string sENDERField;
        
        private string rECEIVERField;
        
        private string rETURN_NOTEField;
        
        private string aCTION_TYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string ID_TRANSACTION
        {
            get
            {
                return this.iD_TRANSACTIONField;
            }
            set
            {
                this.iD_TRANSACTIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string DOCUMENT_NUMBER
        {
            get
            {
                return this.dOCUMENT_NUMBERField;
            }
            set
            {
                this.dOCUMENT_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string DOCUMENT_DATE
        {
            get
            {
                return this.dOCUMENT_DATEField;
            }
            set
            {
                this.dOCUMENT_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string SENDER
        {
            get
            {
                return this.sENDERField;
            }
            set
            {
                this.sENDERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string RECEIVER
        {
            get
            {
                return this.rECEIVERField;
            }
            set
            {
                this.rECEIVERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string RETURN_NOTE
        {
            get
            {
                return this.rETURN_NOTEField;
            }
            set
            {
                this.rETURN_NOTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string ACTION_TYPE
        {
            get
            {
                return this.aCTION_TYPEField;
            }
            set
            {
                this.aCTION_TYPEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE")]
    public partial class CarrierDetailResult
    {
        
        private string cARRIER_LABEL1Field;
        
        private string cARRIER_LABEL2Field;
        
        private string gTINField;
        
        private string lOT_NUMBERField;
        
        private string pRODUCTION_DATEField;
        
        private string eXPIRATION_DATEField;
        
        private string pRODUCT_NOTEField;
        
        private string sERIAL_NUMBERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string CARRIER_LABEL1
        {
            get
            {
                return this.cARRIER_LABEL1Field;
            }
            set
            {
                this.cARRIER_LABEL1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string CARRIER_LABEL2
        {
            get
            {
                return this.cARRIER_LABEL2Field;
            }
            set
            {
                this.cARRIER_LABEL2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string GTIN
        {
            get
            {
                return this.gTINField;
            }
            set
            {
                this.gTINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string LOT_NUMBER
        {
            get
            {
                return this.lOT_NUMBERField;
            }
            set
            {
                this.lOT_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string PRODUCTION_DATE
        {
            get
            {
                return this.pRODUCTION_DATEField;
            }
            set
            {
                this.pRODUCTION_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string EXPIRATION_DATE
        {
            get
            {
                return this.eXPIRATION_DATEField;
            }
            set
            {
                this.eXPIRATION_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string PRODUCT_NOTE
        {
            get
            {
                return this.pRODUCT_NOTEField;
            }
            set
            {
                this.pRODUCT_NOTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string SERIAL_NUMBER
        {
            get
            {
                return this.sERIAL_NUMBERField;
            }
            set
            {
                this.sERIAL_NUMBERField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE")]
    public partial class NotificationResultSerial
    {
        
        private string iD_TRANSACTIONField;
        
        private string tRANSACTION_CODEField;
        
        private string tRANSACTION_MESSAGEField;
        
        private string sERIAL_NUMBERField;
        
        private string gTINField;
        
        private string lOT_NUMBERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string ID_TRANSACTION
        {
            get
            {
                return this.iD_TRANSACTIONField;
            }
            set
            {
                this.iD_TRANSACTIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string TRANSACTION_CODE
        {
            get
            {
                return this.tRANSACTION_CODEField;
            }
            set
            {
                this.tRANSACTION_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string TRANSACTION_MESSAGE
        {
            get
            {
                return this.tRANSACTION_MESSAGEField;
            }
            set
            {
                this.tRANSACTION_MESSAGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string SERIAL_NUMBER
        {
            get
            {
                return this.sERIAL_NUMBERField;
            }
            set
            {
                this.sERIAL_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string GTIN
        {
            get
            {
                return this.gTINField;
            }
            set
            {
                this.gTINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string LOT_NUMBER
        {
            get
            {
                return this.lOT_NUMBERField;
            }
            set
            {
                this.lOT_NUMBERField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE")]
    public partial class NotificationResultGlobal
    {
        
        private string gLOBAL_ERROR_CODEField;
        
        private string gLOBAL_ERROR_MSGField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string GLOBAL_ERROR_CODE
        {
            get
            {
                return this.gLOBAL_ERROR_CODEField;
            }
            set
            {
                this.gLOBAL_ERROR_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string GLOBAL_ERROR_MSG
        {
            get
            {
                return this.gLOBAL_ERROR_MSGField;
            }
            set
            {
                this.gLOBAL_ERROR_MSGField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE")]
    public partial class Country_Detail
    {
        
        private string iD_COUNTRYField;
        
        private string cOUNTRY_NAMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string ID_COUNTRY
        {
            get
            {
                return this.iD_COUNTRYField;
            }
            set
            {
                this.iD_COUNTRYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string COUNTRY_NAME
        {
            get
            {
                return this.cOUNTRY_NAMEField;
            }
            set
            {
                this.cOUNTRY_NAMEField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TransactionListProduction", WrapperNamespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", IsWrapped=true)]
    public partial class TransactionListProductionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string Key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string GLN_PN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<System.DateTime> StartDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<System.DateTime> EndDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string DocumentNumber;
        
        public TransactionListProductionRequest()
        {
        }
        
        public TransactionListProductionRequest(string Key, string GLN_PN, System.Nullable<System.DateTime> StartDate, System.Nullable<System.DateTime> EndDate, string DocumentNumber)
        {
            this.Key = Key;
            this.GLN_PN = GLN_PN;
            this.StartDate = StartDate;
            this.EndDate = EndDate;
            this.DocumentNumber = DocumentNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TransactionListProductionResponse", WrapperNamespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", IsWrapped=true)]
    public partial class TransactionListProductionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("result", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public BildirimService.TransactionListProductionResult[] result;
        
        public TransactionListProductionResponse()
        {
        }
        
        public TransactionListProductionResponse(BildirimService.TransactionListProductionResult[] result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCountryName", WrapperNamespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", IsWrapped=true)]
    public partial class GetCountryNameRequest
    {
        
        public GetCountryNameRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCountryNameResponse", WrapperNamespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", IsWrapped=true)]
    public partial class GetCountryNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Country_Detail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public BildirimService.Country_Detail[] Country_Detail;
        
        public GetCountryNameResponse()
        {
        }
        
        public GetCountryNameResponse(BildirimService.Country_Detail[] Country_Detail)
        {
            this.Country_Detail = Country_Detail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendXMLNotification_Dealer", WrapperNamespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", IsWrapped=true)]
    public partial class SendXMLNotification_DealerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string XMLText;
        
        public SendXMLNotification_DealerRequest()
        {
        }
        
        public SendXMLNotification_DealerRequest(string XMLText)
        {
            this.XMLText = XMLText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendXMLNotification_DealerResponse", WrapperNamespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", IsWrapped=true)]
    public partial class SendXMLNotification_DealerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public BildirimService.NotificationResultGlobal NotificationResultGlobal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("NotificationResultSerial", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public BildirimService.NotificationResultSerial[] NotificationResultSerial;
        
        public SendXMLNotification_DealerResponse()
        {
        }
        
        public SendXMLNotification_DealerResponse(BildirimService.NotificationResultGlobal NotificationResultGlobal, BildirimService.NotificationResultSerial[] NotificationResultSerial)
        {
            this.NotificationResultGlobal = NotificationResultGlobal;
            this.NotificationResultSerial = NotificationResultSerial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CarrierDetailList", WrapperNamespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", IsWrapped=true)]
    public partial class CarrierDetailListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string Key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string GLN_PN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string CarrierType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string CarrierLabel;
        
        public CarrierDetailListRequest()
        {
        }
        
        public CarrierDetailListRequest(string Key, string GLN_PN, string CarrierType, string CarrierLabel)
        {
            this.Key = Key;
            this.GLN_PN = GLN_PN;
            this.CarrierType = CarrierType;
            this.CarrierLabel = CarrierLabel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CarrierDetailListResponse", WrapperNamespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", IsWrapped=true)]
    public partial class CarrierDetailListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CarrierDetailResult", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public BildirimService.CarrierDetailResult[] CarrierDetailResult;
        
        public CarrierDetailListResponse()
        {
        }
        
        public CarrierDetailListResponse(BildirimService.CarrierDetailResult[] CarrierDetailResult)
        {
            this.CarrierDetailResult = CarrierDetailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CarrierDetailList_Wholesaler", WrapperNamespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", IsWrapped=true)]
    public partial class CarrierDetailList_WholesalerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string Key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string GLN_PN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string CarrierType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string CarrierLabel;
        
        public CarrierDetailList_WholesalerRequest()
        {
        }
        
        public CarrierDetailList_WholesalerRequest(string Key, string GLN_PN, string CarrierType, string CarrierLabel)
        {
            this.Key = Key;
            this.GLN_PN = GLN_PN;
            this.CarrierType = CarrierType;
            this.CarrierLabel = CarrierLabel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CarrierDetailList_WholesalerResponse", WrapperNamespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", IsWrapped=true)]
    public partial class CarrierDetailList_WholesalerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CarrierDetailResult", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public BildirimService.CarrierDetailResult[] CarrierDetailResult;
        
        public CarrierDetailList_WholesalerResponse()
        {
        }
        
        public CarrierDetailList_WholesalerResponse(BildirimService.CarrierDetailResult[] CarrierDetailResult)
        {
            this.CarrierDetailResult = CarrierDetailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TransactionList", WrapperNamespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", IsWrapped=true)]
    public partial class TransactionListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string Key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string GLN_PN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<System.DateTime> StartDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<System.DateTime> EndDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string DocumentNumber;
        
        public TransactionListRequest()
        {
        }
        
        public TransactionListRequest(string Key, string GLN_PN, System.Nullable<System.DateTime> StartDate, System.Nullable<System.DateTime> EndDate, string DocumentNumber)
        {
            this.Key = Key;
            this.GLN_PN = GLN_PN;
            this.StartDate = StartDate;
            this.EndDate = EndDate;
            this.DocumentNumber = DocumentNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TransactionListResponse", WrapperNamespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", IsWrapped=true)]
    public partial class TransactionListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("TransactionResult", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public BildirimService.TransactionResult[] TransactionResult;
        
        public TransactionListResponse()
        {
        }
        
        public TransactionListResponse(BildirimService.TransactionResult[] TransactionResult)
        {
            this.TransactionResult = TransactionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCompanyName", WrapperNamespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", IsWrapped=true)]
    public partial class GetCompanyNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string IdTaxNo;
        
        public GetCompanyNameRequest()
        {
        }
        
        public GetCompanyNameRequest(string IdTaxNo)
        {
            this.IdTaxNo = IdTaxNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCompanyNameResponse", WrapperNamespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", IsWrapped=true)]
    public partial class GetCompanyNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string COMPANY_NAME;
        
        public GetCompanyNameResponse()
        {
        }
        
        public GetCompanyNameResponse(string COMPANY_NAME)
        {
            this.COMPANY_NAME = COMPANY_NAME;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendXMLNotification", WrapperNamespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", IsWrapped=true)]
    public partial class SendXMLNotificationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string XMLText;
        
        public SendXMLNotificationRequest()
        {
        }
        
        public SendXMLNotificationRequest(string XMLText)
        {
            this.XMLText = XMLText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendXMLNotificationResponse", WrapperNamespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", IsWrapped=true)]
    public partial class SendXMLNotificationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public BildirimService.NotificationResultGlobal NotificationResultGlobal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("NotificationResultSerial", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public BildirimService.NotificationResultSerial[] NotificationResultSerial;
        
        public SendXMLNotificationResponse()
        {
        }
        
        public SendXMLNotificationResponse(BildirimService.NotificationResultGlobal NotificationResultGlobal, BildirimService.NotificationResultSerial[] NotificationResultSerial)
        {
            this.NotificationResultGlobal = NotificationResultGlobal;
            this.NotificationResultSerial = NotificationResultSerial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StockCheck", WrapperNamespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", IsWrapped=true)]
    public partial class StockCheckRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string Key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string GLN_PN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<short> CompanyType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string CarrierType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string CarrierLabel;
        
        public StockCheckRequest()
        {
        }
        
        public StockCheckRequest(string Key, string GLN_PN, System.Nullable<short> CompanyType, string CarrierType, string CarrierLabel)
        {
            this.Key = Key;
            this.GLN_PN = GLN_PN;
            this.CompanyType = CompanyType;
            this.CarrierType = CarrierType;
            this.CarrierLabel = CarrierLabel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StockCheckResponse", WrapperNamespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", IsWrapped=true)]
    public partial class StockCheckResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int> ResultCode;
        
        public StockCheckResponse()
        {
        }
        
        public StockCheckResponse(System.Nullable<int> ResultCode)
        {
            this.ResultCode = ResultCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCompanyNameByGLN_PN", WrapperNamespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", IsWrapped=true)]
    public partial class GetCompanyNameByGLN_PNRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string GLN_PN;
        
        public GetCompanyNameByGLN_PNRequest()
        {
        }
        
        public GetCompanyNameByGLN_PNRequest(string GLN_PN)
        {
            this.GLN_PN = GLN_PN;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCompanyNameByGLN_PNResponse", WrapperNamespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", IsWrapped=true)]
    public partial class GetCompanyNameByGLN_PNResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string COMPANY_NAME;
        
        public GetCompanyNameByGLN_PNResponse()
        {
        }
        
        public GetCompanyNameByGLN_PNResponse(string COMPANY_NAME)
        {
            this.COMPANY_NAME = COMPANY_NAME;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetHistory", WrapperNamespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", IsWrapped=true)]
    public partial class GetHistoryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string GTIN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string SerialNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string LotNumber;
        
        public GetHistoryRequest()
        {
        }
        
        public GetHistoryRequest(string GTIN, string SerialNumber, string LotNumber)
        {
            this.GTIN = GTIN;
            this.SerialNumber = SerialNumber;
            this.LotNumber = LotNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetHistoryResponse", WrapperNamespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", IsWrapped=true)]
    public partial class GetHistoryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("History_Detail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public BildirimService.History_Detail[] History_Detail;
        
        public GetHistoryResponse()
        {
        }
        
        public GetHistoryResponse(BildirimService.History_Detail[] History_Detail)
        {
            this.History_Detail = History_Detail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendXMLNotification_Wholesaler", WrapperNamespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", IsWrapped=true)]
    public partial class SendXMLNotification_WholesalerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string XMLText;
        
        public SendXMLNotification_WholesalerRequest()
        {
        }
        
        public SendXMLNotification_WholesalerRequest(string XMLText)
        {
            this.XMLText = XMLText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendXMLNotification_WholesalerResponse", WrapperNamespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", IsWrapped=true)]
    public partial class SendXMLNotification_WholesalerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public BildirimService.NotificationResultGlobal NotificationResultGlobal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("NotificationResultSerial", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public BildirimService.NotificationResultSerial[] NotificationResultSerial;
        
        public SendXMLNotification_WholesalerResponse()
        {
        }
        
        public SendXMLNotification_WholesalerResponse(BildirimService.NotificationResultGlobal NotificationResultGlobal, BildirimService.NotificationResultSerial[] NotificationResultSerial)
        {
            this.NotificationResultGlobal = NotificationResultGlobal;
            this.NotificationResultSerial = NotificationResultSerial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TransactionDetailList", WrapperNamespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", IsWrapped=true)]
    public partial class TransactionDetailListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string IdTransaction;
        
        public TransactionDetailListRequest()
        {
        }
        
        public TransactionDetailListRequest(string IdTransaction)
        {
            this.IdTransaction = IdTransaction;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TransactionDetailListResponse", WrapperNamespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", IsWrapped=true)]
    public partial class TransactionDetailListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("TransactionDetailResult", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public BildirimService.TransactionDetailResult[] TransactionDetailResult;
        
        public TransactionDetailListResponse()
        {
        }
        
        public TransactionDetailListResponse(BildirimService.TransactionDetailResult[] TransactionDetailResult)
        {
            this.TransactionDetailResult = TransactionDetailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CarrierDetailList_Dealer", WrapperNamespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", IsWrapped=true)]
    public partial class CarrierDetailList_DealerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string Key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string GLN_PN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string CarrierType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string CarrierLabel;
        
        public CarrierDetailList_DealerRequest()
        {
        }
        
        public CarrierDetailList_DealerRequest(string Key, string GLN_PN, string CarrierType, string CarrierLabel)
        {
            this.Key = Key;
            this.GLN_PN = GLN_PN;
            this.CarrierType = CarrierType;
            this.CarrierLabel = CarrierLabel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CarrierDetailList_DealerResponse", WrapperNamespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", IsWrapped=true)]
    public partial class CarrierDetailList_DealerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CarrierDetailResult", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public BildirimService.CarrierDetailResult[] CarrierDetailResult;
        
        public CarrierDetailList_DealerResponse()
        {
        }
        
        public CarrierDetailList_DealerResponse(BildirimService.CarrierDetailResult[] CarrierDetailResult)
        {
            this.CarrierDetailResult = CarrierDetailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProductName", WrapperNamespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", IsWrapped=true)]
    public partial class GetProductNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string GTIN;
        
        public GetProductNameRequest()
        {
        }
        
        public GetProductNameRequest(string GTIN)
        {
            this.GTIN = GTIN;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProductNameResponse", WrapperNamespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", IsWrapped=true)]
    public partial class GetProductNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sinerji-srv1/BKST_EXT.Services:BKST_EXT_READ_SERVICE", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string PRODUCT_NAME;
        
        public GetProductNameResponse()
        {
        }
        
        public GetProductNameResponse(string PRODUCT_NAME)
        {
            this.PRODUCT_NAME = PRODUCT_NAME;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface BKST_EXT_READ_SERVICE_PortTypeChannel : BildirimService.BKST_EXT_READ_SERVICE_PortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class BKST_EXT_READ_SERVICE_PortTypeClient : System.ServiceModel.ClientBase<BildirimService.BKST_EXT_READ_SERVICE_PortType>, BildirimService.BKST_EXT_READ_SERVICE_PortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BKST_EXT_READ_SERVICE_PortTypeClient() : 
                base(BKST_EXT_READ_SERVICE_PortTypeClient.GetDefaultBinding(), BKST_EXT_READ_SERVICE_PortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BKST_EXT_Services_BKST_EXT_READ_SERVICE_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BKST_EXT_READ_SERVICE_PortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(BKST_EXT_READ_SERVICE_PortTypeClient.GetBindingForEndpoint(endpointConfiguration), BKST_EXT_READ_SERVICE_PortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BKST_EXT_READ_SERVICE_PortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BKST_EXT_READ_SERVICE_PortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BKST_EXT_READ_SERVICE_PortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BKST_EXT_READ_SERVICE_PortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BKST_EXT_READ_SERVICE_PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public BildirimService.KeyStatusCheckResponse KeyStatusCheck(BildirimService.KeyStatusCheckRequest request)
        {
            return base.Channel.KeyStatusCheck(request);
        }
        
        public System.Threading.Tasks.Task<BildirimService.KeyStatusCheckResponse> KeyStatusCheckAsync(BildirimService.KeyStatusCheckRequest request)
        {
            return base.Channel.KeyStatusCheckAsync(request);
        }
        
        public BildirimService.TransactionListProductionResponse TransactionListProduction(BildirimService.TransactionListProductionRequest request)
        {
            return base.Channel.TransactionListProduction(request);
        }
        
        public System.Threading.Tasks.Task<BildirimService.TransactionListProductionResponse> TransactionListProductionAsync(BildirimService.TransactionListProductionRequest request)
        {
            return base.Channel.TransactionListProductionAsync(request);
        }
        
        public BildirimService.GetCountryNameResponse GetCountryName(BildirimService.GetCountryNameRequest request)
        {
            return base.Channel.GetCountryName(request);
        }
        
        public System.Threading.Tasks.Task<BildirimService.GetCountryNameResponse> GetCountryNameAsync(BildirimService.GetCountryNameRequest request)
        {
            return base.Channel.GetCountryNameAsync(request);
        }
        
        public BildirimService.SendXMLNotification_DealerResponse SendXMLNotification_Dealer(BildirimService.SendXMLNotification_DealerRequest request)
        {
            return base.Channel.SendXMLNotification_Dealer(request);
        }
        
        public System.Threading.Tasks.Task<BildirimService.SendXMLNotification_DealerResponse> SendXMLNotification_DealerAsync(BildirimService.SendXMLNotification_DealerRequest request)
        {
            return base.Channel.SendXMLNotification_DealerAsync(request);
        }
        
        public BildirimService.CarrierDetailListResponse CarrierDetailList(BildirimService.CarrierDetailListRequest request)
        {
            return base.Channel.CarrierDetailList(request);
        }
        
        public System.Threading.Tasks.Task<BildirimService.CarrierDetailListResponse> CarrierDetailListAsync(BildirimService.CarrierDetailListRequest request)
        {
            return base.Channel.CarrierDetailListAsync(request);
        }
        
        public BildirimService.CarrierDetailList_WholesalerResponse CarrierDetailList_Wholesaler(BildirimService.CarrierDetailList_WholesalerRequest request)
        {
            return base.Channel.CarrierDetailList_Wholesaler(request);
        }
        
        public System.Threading.Tasks.Task<BildirimService.CarrierDetailList_WholesalerResponse> CarrierDetailList_WholesalerAsync(BildirimService.CarrierDetailList_WholesalerRequest request)
        {
            return base.Channel.CarrierDetailList_WholesalerAsync(request);
        }
        
        public BildirimService.TransactionListResponse TransactionList(BildirimService.TransactionListRequest request)
        {
            return base.Channel.TransactionList(request);
        }
        
        public System.Threading.Tasks.Task<BildirimService.TransactionListResponse> TransactionListAsync(BildirimService.TransactionListRequest request)
        {
            return base.Channel.TransactionListAsync(request);
        }
        
        public BildirimService.GetCompanyNameResponse GetCompanyName(BildirimService.GetCompanyNameRequest request)
        {
            return base.Channel.GetCompanyName(request);
        }
        
        public System.Threading.Tasks.Task<BildirimService.GetCompanyNameResponse> GetCompanyNameAsync(BildirimService.GetCompanyNameRequest request)
        {
            return base.Channel.GetCompanyNameAsync(request);
        }
        
        public BildirimService.SendXMLNotificationResponse SendXMLNotification(BildirimService.SendXMLNotificationRequest request)
        {
            return base.Channel.SendXMLNotification(request);
        }
        
        public System.Threading.Tasks.Task<BildirimService.SendXMLNotificationResponse> SendXMLNotificationAsync(BildirimService.SendXMLNotificationRequest request)
        {
            return base.Channel.SendXMLNotificationAsync(request);
        }
        
        public BildirimService.StockCheckResponse StockCheck(BildirimService.StockCheckRequest request)
        {
            return base.Channel.StockCheck(request);
        }
        
        public System.Threading.Tasks.Task<BildirimService.StockCheckResponse> StockCheckAsync(BildirimService.StockCheckRequest request)
        {
            return base.Channel.StockCheckAsync(request);
        }
        
        public BildirimService.GetCompanyNameByGLN_PNResponse GetCompanyNameByGLN_PN(BildirimService.GetCompanyNameByGLN_PNRequest request)
        {
            return base.Channel.GetCompanyNameByGLN_PN(request);
        }
        
        public System.Threading.Tasks.Task<BildirimService.GetCompanyNameByGLN_PNResponse> GetCompanyNameByGLN_PNAsync(BildirimService.GetCompanyNameByGLN_PNRequest request)
        {
            return base.Channel.GetCompanyNameByGLN_PNAsync(request);
        }
        
        public BildirimService.GetHistoryResponse GetHistory(BildirimService.GetHistoryRequest request)
        {
            return base.Channel.GetHistory(request);
        }
        
        public System.Threading.Tasks.Task<BildirimService.GetHistoryResponse> GetHistoryAsync(BildirimService.GetHistoryRequest request)
        {
            return base.Channel.GetHistoryAsync(request);
        }
        
        public BildirimService.SendXMLNotification_WholesalerResponse SendXMLNotification_Wholesaler(BildirimService.SendXMLNotification_WholesalerRequest request)
        {
            return base.Channel.SendXMLNotification_Wholesaler(request);
        }
        
        public System.Threading.Tasks.Task<BildirimService.SendXMLNotification_WholesalerResponse> SendXMLNotification_WholesalerAsync(BildirimService.SendXMLNotification_WholesalerRequest request)
        {
            return base.Channel.SendXMLNotification_WholesalerAsync(request);
        }
        
        public BildirimService.TransactionDetailListResponse TransactionDetailList(BildirimService.TransactionDetailListRequest request)
        {
            return base.Channel.TransactionDetailList(request);
        }
        
        public System.Threading.Tasks.Task<BildirimService.TransactionDetailListResponse> TransactionDetailListAsync(BildirimService.TransactionDetailListRequest request)
        {
            return base.Channel.TransactionDetailListAsync(request);
        }
        
        public BildirimService.CarrierDetailList_DealerResponse CarrierDetailList_Dealer(BildirimService.CarrierDetailList_DealerRequest request)
        {
            return base.Channel.CarrierDetailList_Dealer(request);
        }
        
        public System.Threading.Tasks.Task<BildirimService.CarrierDetailList_DealerResponse> CarrierDetailList_DealerAsync(BildirimService.CarrierDetailList_DealerRequest request)
        {
            return base.Channel.CarrierDetailList_DealerAsync(request);
        }
        
        public BildirimService.GetProductNameResponse GetProductName(BildirimService.GetProductNameRequest request)
        {
            return base.Channel.GetProductName(request);
        }
        
        public System.Threading.Tasks.Task<BildirimService.GetProductNameResponse> GetProductNameAsync(BildirimService.GetProductNameRequest request)
        {
            return base.Channel.GetProductNameAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BKST_EXT_Services_BKST_EXT_READ_SERVICE_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BKST_EXT_Services_BKST_EXT_READ_SERVICE_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://soa5.trgm.local:5555/ws/BKST_EXT.Services.BKST_EXT_READ_SERVICE/BKST_EXT_S" +
                        "ervices_BKST_EXT_READ_SERVICE_Port");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return BKST_EXT_READ_SERVICE_PortTypeClient.GetBindingForEndpoint(EndpointConfiguration.BKST_EXT_Services_BKST_EXT_READ_SERVICE_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return BKST_EXT_READ_SERVICE_PortTypeClient.GetEndpointAddress(EndpointConfiguration.BKST_EXT_Services_BKST_EXT_READ_SERVICE_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            BKST_EXT_Services_BKST_EXT_READ_SERVICE_Port,
        }
    }
}
